version: '3'
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:81"
      - "444:444"
      - "27017:27017"
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  caddy_data:  
  caddy_config:  
