version: '3'
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  caddy_data:  
  caddy_config:  
